mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('questions/', views.PollsView.as_view(), name='questions'),
    path('contact/', views.ContactCreate.as_view(), name='contact'),
    path('<int:pk>/', views.CvView.as_view(), name='cv'),
    path('<int:pk>/details/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    message = models.TextField(max_length=400)
    pub_date = models.DateTimeField(auto_now=True)
    cv_Img = models.ImageField(upload_to='images/') 

    def __str__(self):
        return f"{self.first_name} {self.last_name}, Skills: {self.message}"
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

polls/forms.py
from django.forms import ModelForm
from django.forms import Textarea
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ["first_name", "last_name", "message", "cv_Img"]
        widgets = {
            "message": Textarea(
                attrs={
                    "placeholder": "Put your skills here"
                }
            )
        }

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import Choice, Question, Contact

class ContactCreate(generic.CreateView):
    template_name = 'polls/contact_forms.html'
    model = Contact
    fields = ["first_name", "last_name", "message", "cv_Img"]
    success_url = reverse_lazy('polls:index')

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_cv_list'

    def get_queryset(self):
        """Return the last 50 published CV."""
        contains = self.request.GET.get('contains')
        if contains is None:
            return Contact.objects.order_by('-pub_date')
        return Contact.objects.order_by('-pub_date').filter(message__contains=contains)[:50]

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['skills_contains'] = Contact.objects.all().filter(message__contains="")
        return context

class PollsView(generic.ListView):
    template_name = 'polls/polls.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class CvView(generic.DetailView):
    model = Contact
    template_name = 'polls/cv.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>CV list</title>
  </head>
  <body>
          {% block content %}
          {% endblock %}
  </body>
</html>

templates/polls/contact_forms.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data" action="{% url 'polls:contact' %}"> 
    {% csrf_token %}
    {{ form }}
    <button type="submit">Envoyer mon CV</button>
</form>
<a href="{% url 'polls:index' %}">Retour à la liste</a>
{% endblock %}

templates/polls/cv.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ contact.first_name }} {{ contact.last_name }}</h1>

<img src="{{ contact.cv_Img.url }}" class="img-responsive" style="height: 150px; width: 150px;" /> 

<div>Compétences : {{ contact.message }}</div>

<a href="{% url 'polls:index' %}">Retour à la liste</a>
{% endblock %}

templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
{% endblock %}

templates/polls/index.html
{% extends 'base.html' %}
{% load static %}
{% load tag %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<div id="flex"> 
    <div><span>Pour filtrer par skill : </span>
    <form action="{%url 'polls:index' %}"  method="get">
        <input type="text" name="contains" placeholder="Search...">
        <button  type="submit">Filtrer</button>
     </form>
    </div>
    <div id="add" >
        <a href="{% url 'polls:contact' %}">Ajouter son CV</a>
    </div>
     </div>
        <div id="cards_landscape_wrap-2">
            <div class="container">
                <div class="row">
                    {% if latest_cv_list  %}
                    {% for contact in latest_cv_list %}
                    <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">

                                <a href="{% url 'polls:cv' contact.id %}">
                                    <div class="card-flyer">
                                        <div class="text-box">
                                            <div class="image-box">
                                                <img src="{{ contact.cv_Img.url }}" alt="" />
                                            </div>
                                            <div class="text-container">
                                                <h6>{{ contact.first_name }} {{ contact.last_name }} </h6>
                                                <p>Skills: {{ contact.message }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                    {% endfor %}
                    {% else %}
                    <p>No CV are available.</p>
                {% endif %}
                </div>
            </div>
        </div>
    

         {% endblock %}

templates/polls/polls.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}